// Short (1-sentence) definitions used for inline hover tooltips throughout the app.
// Full definitions live in GlossaryPage.jsx.
export const GLOSSARY_TOOLTIPS = {
  'CDN': 'A global network of servers that delivers your content from locations close to each user, reducing load times.',
  'Serverless': 'Run code without managing servers — you pay only for the milliseconds your function executes.',
  'Kubernetes': 'An open-source system that automates deploying, scaling, and managing containerised applications.',
  'Managed Kubernetes': 'A hosted Kubernetes service where the cloud provider manages the control plane for you.',
  'Managed databases': 'Cloud-hosted databases where the provider handles backups, patching, and failover automatically.',
  'Serverless functions': 'Event-driven functions that run on demand with no server management required.',
  'AI / ML APIs': 'Pre-built machine learning services (vision, NLP, speech) accessible via a simple API call.',
  'Multi-region': 'The ability to deploy your app across multiple geographic regions for lower latency and redundancy.',
  'Global edge network': 'A distributed network of servers at the "edge" of the internet, close to end users worldwide.',
  'DDoS protection': 'Automated defence against Distributed Denial-of-Service attacks that flood your infrastructure with traffic.',
  '99.9%+ SLA': 'A contractual uptime guarantee — 99.9% allows ~8.7 hours of downtime per year.',
  'GDPR': 'EU regulation requiring lawful handling and protection of personal data for European residents.',
  'HIPAA eligible': 'The provider can sign a Business Associate Agreement, enabling storage of US healthcare data.',
  'SOC 2': 'An auditing framework verifying a provider\'s security, availability, and data confidentiality controls.',
  'ISO 27001': 'An international standard for information security management systems.',
  'Terraform support': 'Infrastructure as Code — define and provision cloud resources using declarative config files.',
  'GitHub integration': 'Native connectivity with GitHub for automated deployments and CI/CD pipelines.',
  'Built-in CDN': 'A content delivery network included natively with the platform — no third-party setup needed.',
  'Geographic coverage': 'How many regions and countries the provider has data centres in.',
  'VPC': 'Virtual Private Cloud — an isolated network within the cloud that only your resources can access.',
  'IaaS': 'Infrastructure as a Service — raw compute, storage, and networking that you manage yourself.',
  'PaaS': 'Platform as a Service — a managed environment where you deploy code without touching the OS or infra.',
  'SaaS': 'Software as a Service — fully hosted software you access over the internet on a subscription.',
  'Edge computing': 'Running code on servers physically close to end users (at the "edge" of the internet) instead of a central data centre, reducing latency.',
  'Edge Functions': 'Serverless functions deployed to edge locations worldwide so they execute as close as possible to each user.',
  'Workers': "Cloudflare's edge compute platform — lightweight JavaScript/WASM functions running on 300+ servers globally.",
  'R2': "Cloudflare's S3-compatible object storage with zero egress fees — you pay only for storage, never for downloads.",
  'D1': "Cloudflare's serverless SQLite database, replicated to the edge for low-latency reads worldwide.",
  'Egress fees': 'Charges applied when data leaves a cloud provider — moving data out to the internet or to another provider. Cloudflare R2 charges zero egress fees.',
  'JAMstack': 'A web architecture using pre-built markup, JavaScript, and APIs. Sites are deployed as static files to a CDN — fast, cheap, and secure.',
  'Cold start': 'The delay that occurs when a serverless function or free-tier service starts up after a period of inactivity.',
  'Object storage': 'A flat data storage system for files, images, backups, and large datasets — accessed via HTTP (e.g. AWS S3, Cloudflare R2).',
};
